apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: xxmadmanxx/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src:  '**/*.js'
            dest: .
          - src:  '**/*.css'
            dest: .
          - src:  '**/*.html'
            dest: .
    - image: xxmadmanxx/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: xxmadmanxx/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: xxmadmanxx/multi-randgen
      context: randgen
      docker:
        dockerfile: Dockerfile.dev

